services:
  backend:
    image: yahkerobertkertasnya/splanngo:latest
    tty: true
    build: .
    ports:
      - "3910:3900"
    restart: on-failure
    depends_on:
      - mysql
    networks:
      - splanngo

  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--lower_case_table_names=1']
    container_name: splanngo-mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_TCP_PORT=${DATABASE_PORT}
    restart: always
    networks:
      - splanngo
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  splanngo:
    external: true

volumes:
  mysql-data:
