services:
  backend:
    image: yahkerobertkertasnya/splanngo:latest
    tty: true
    build: .
    ports:
      - "3900:3900"
    restart: always
    depends_on:
      - mysql
    networks:
      - splanngo

  mysql:
    image: mysql:5.7
    container_name: splanngo-mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_TCP_PORT=${DATABASE_PORT}
    restart: always
    networks:
      - splanngo
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  splanngo:
    driver: bridge


volumes:
  mysql-data: